- name: Run To-Do App
  hosts: webservers
  remote_user: ec2-user

  vars_prompt:
    - name: secret_key
      prompt: What is the Secret Key?
    - name: trello_api_key
      prompt: What is the Trello API key?
    - name: trello_api_token
      prompt: What is the Trello API token?
    - name: trello_board_id
      prompt: What is the Trello board id?
    - name: trello_todo_list_id
      prompt: What is the Trello todo list id?
    - name: trello_doing_list_id
      prompt: What is the Trello doing list id?
    - name: trello_done_list_id
      prompt: What is the Trello done list id?

  tasks:
    - name: Install Git and Python3
      ansible.builtin.yum:
        name:
          - git
          - python311
      become: true

    - name: Install Poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3.11 -
        creates: "/home/ec2-user/.local/bin/poetry"

    - name: Create To-Do App directory
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
        owner: ec2-user
        mode: "755"
      become: true

    - name: Git checkout To-Do App repo
      ansible.builtin.git:
        repo: "https://github.com/thebauSoftwire/DevOps-Course-Starter.git"
        dest: /opt/todoapp
        version: "ex4-vm-provisioning-ansible"

    - name: Install project dependencies
      ansible.builtin.shell:
        cmd: /home/ec2-user/.local/bin/poetry install
        chdir: /opt/todoapp

    - name: Create .env file from template
      ansible.builtin.template:
        src: /home/ec2-user/.env.j2
        dest: /opt/todoapp/.env

    - name: Copy todoapp.service to systemd on host
      ansible.builtin.copy:
        src: /home/ec2-user/todoapp.service
        dest: /etc/systemd/system/todoapp.service
      become: yes

    - name: Add systemd task to To-Do app
      ansible.builtin.systemd_service:
        state: restarted
        name: todoapp.service
        daemon_reload: true
      become: yes
