name: Continuous Integration
on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag todo-app:test --target test --platform linux/amd64 .
      - run: docker run todo-app:test
  deploy:
    name: Publish to Docker Hub and deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/ex9' }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:prod --target production --platform linux/amd64 .
      - name: Publish to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:prod
